name: Project build
on: [ push, create ]
env:
  DOWNLOAD_URL_BASE: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${GITHUB_REF#refs/*/}
jobs:
  make-firmware:
    name: Compile firmware
    runs-on: ubuntu-latest
    env:
      REF: ${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup safe directory for git
        run: |
          repo=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}
          git config --global --add safe.directory /__w/${repo}/${repo}
      - name: Build firmware (at a push)
        if: github.event_name == 'push'
        run: |
          make docker
          make init
          make firmware
